spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
booking:
  property: Booking Profile Dev