spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb?authSource=admin
product:
  property: Product Profile Dev
app:
  testProp: Propiedad de prueba ACTUALIZADA CINCO (con refresh)
